### ISSUE TITLE
Capture screenshot

### ISSUE THREAD

**Issue by mortenboye** [ardera/flutter-pi#263]
Is it possible to capture a screenshot of a running Flutter-pi app?

I've tried with [fbgrab](https://github.com/GunnarMonell/fbgrab) but I can only get it to capture an empty terminal prompt, not the app.

Any ideas?

**Comment by mortenboye** [comment]
I ended up doing it within my app, using https://pub.dev/packages/screenshot

Closing

**Comment by SimonJFisherMB** [comment]
This is something I would like to do also. I have a full (800x440) screen app running on flutter_pi and would like to be able to capture a screenshot to file in order to remotely see what's on the screen for support purposes. I've tried a DRM screenshot (C) app but just returns a completely black bitmap.
