### ISSUE TITLE
Support Vulkan

### ISSUE THREAD

**Issue by DisDis** [ardera/flutter-pi#63]
https://github.com/ardera/flutter-pi/tree/engine-binaries
I know flutter engine can work with Vulkan, if it is compiled with flag.
(I have builded engine 1 year ago, also i have experimented with release mode and snapshot, but result is fail.)
I am ready try install RaPi V3D 4.2 (if i find it :) )

RaPi4 has early support Vulkan now.
https://www.youtube.com/watch?v=ygBB3D5vryw
https://www.raspberrypi.org/blog/vulkan-update-now-with-added-source-code/
But this gives a performance boost.

**Comment by ardera** [comment]
While the engine may support vulkan, the API that flutter provides to embedders does not. It only provides software rendering and opengl (& gl es) support.

If the flutter team decides to add vulkan support to the embedder API, I'll consider this, but even then its not sure. The EGL & GL combo is really nice, advanced and widely used for embedder graphics. It also has a lot of extensions for this use case.

I'm gonna close this for now. If you'd like to create a feature request for the flutter to expose vulkan via the embedder api, you can do that & link that issue here.

If that feature makes it into the engine I'm gonna reopen this.

**Comment by doesnotexist** [comment]
Looks like vulkan rendering is supported now:
https://github.com/ardera/flutter-pi/commit/c0a1ca09bbabd2f7da029ea1a4b352627d200bab

**Comment by ardera** [comment]
Yep, though only in that specific refactor branch. There's also a wiki article about it: https://github.com/ardera/flutter-pi/wiki/Running-flutter-pi-with-vulkan
